apply plugin: 'com.android.application'

android {
    namespace 'com.example.android.mynewsapp'
    compileSdk 37
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.example.android.mynewsapp"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

    dependencies {
        implementation libs.camera.camera2.pipe
        coreLibraryDesugaring libs.desugar.jdk.libs
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation libs.recyclerview
        androidTestImplementation libs.androidx.test.ext.junit
        androidTestImplementation libs.androidx.test.runner
        androidTestImplementation libs.espresso.core
        implementation libs.appcompat
        implementation libs.constraintlayout
        implementation libs.loader
        testImplementation libs.junit
    }
